### ISSUE TITLE
admins.xml can't be found

### ISSUE THREAD

**Issue by isedrof** [MIT-Mobile/oidc.mit.edu#4]
Hi, 

I can't find the admins.xml file specified in this line 
<import resource="file:/etc/mitreid-connect/admins.xml" /> in the user-context.xml

**Comment by jricher** [comment]
It's not included in the distribution because it's a security sensitive file, just like the data-context.xml and server-config.xml files. The key is in the same boat.

**Comment by isedrof** [comment]
But can you just give an example ?



2017-01-20 20:02 GMT+01:00 Justin Richer <notifications@github.com>:
